[package]
name = "trust"
version = "0.1.0"
authors = ["Dim"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
proc_macros = { path = "src/proc_macros" }