// This file was auto-generated by scripts/convert_player_item_ids.py
#![allow(dead_code)]

pub const INVENTORY_START: usize = 0;
pub const INVENTORY_END: usize = 57;
pub const INVENTORY_MOUSE_ITEM: usize = 58;
pub const ARMOR_START: usize = 59;
pub const ARMOR_END: usize = 78;
pub const DYES_START: usize = 79;
pub const DYES_END: usize = 88;
pub const MISC_START: usize = 89;
pub const MISC_END: usize = 93;
pub const MISC_DYES_START: usize = 94;
pub const MISC_DYES_END: usize = 98;
pub const BANK_START: usize = 220;
pub const BANK_END: usize = 259;
pub const ARMOR_LOADOUT_0_START: usize = 260;
pub const ARMOR_LOADOUT_0_END: usize = 279;
pub const DYE_LOADOUT_0_START: usize = 280;
pub const DYE_LOADOUT_0_END: usize = 289;
pub const ARMOR_LOADOUT_1_START: usize = 290;
pub const ARMOR_LOADOUT_1_END: usize = 309;
pub const DYE_LOADOUT_1_START: usize = 310;
pub const DYE_LOADOUT_1_END: usize = 319;
pub const ARMOR_LOADOUT_2_START: usize = 320;
pub const ARMOR_LOADOUT_2_END: usize = 339;
pub const DYE_LOADOUT_2_START: usize = 340;
pub const DYE_LOADOUT_2_END: usize = 349;

pub const ARMOR_LOADOUTS_START: &[usize] = &[ARMOR_LOADOUT_0_START, ARMOR_LOADOUT_1_START, ARMOR_LOADOUT_2_START];
pub const ARMOR_LOADOUTS_END: &[usize] = &[ARMOR_LOADOUT_0_END, ARMOR_LOADOUT_1_END, ARMOR_LOADOUT_2_END];
pub const DYE_LOADOUTS_START: &[usize] = &[DYE_LOADOUT_0_START, DYE_LOADOUT_1_START, DYE_LOADOUT_2_START];
pub const DYE_LOADOUTS_END: &[usize] = &[DYE_LOADOUT_0_END, DYE_LOADOUT_1_END, DYE_LOADOUT_2_END];
pub const LOADOUTS_START: &[usize] = ARMOR_LOADOUTS_START;
pub const LOADOUTS_END: &[usize] = DYE_LOADOUTS_END;
