[package]
name = "proc_macros"
version = "0.1.0"
authors = ["Dim"]
edition = "2018"

[dependencies]
syn = { version = "1.0", features = ["extra-traits"] }
proc-macro2 = "1.0"
quote = "1.0"

[lib]
proc-macro = true