// This file was auto-generated by scripts/convert_ids.py
#![allow(dead_code)]

pub const CACHED_INVASIONS: i16 = 3;
pub const CACHED_FROST_MOON: i16 = 1;
pub const CACHED_PUMPKIN_MOON: i16 = 2;
pub const CACHED_OLD_ONES_ARMY: i16 = 3;
pub const NONE: i16 = 0;
pub const GOBLIN_ARMY: i16 = 1;
pub const SNOW_LEGION: i16 = 2;
pub const PIRATE_INVASION: i16 = 3;
pub const MARTIAN_MADNESS: i16 = 4;
